# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4533f843b16c92f31e04de7104320068117a89999a18b52dbb61f50fb33ee6a1fd18a2fdd7b2c55635cb1b5f2406d353cd2e97bf784c9ae54adebcf5e5efc4f0

test:
  secret_key_base: d2c097616c351a429ff6585046823b298998241ba79f28376cd20b23d0dfd5750804bd2d212cdddcd602aea71ace680506fbfd90e7a3a8c4fc536b8a5b78085e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
